[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[package]
name = "ecc-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
rand = "0.8"
log = "0.4"
env_logger = "0.10"
num-traits = "0.2"